### PR TITLE
Feedback two

### PR DESCRIPTION
**Pull request by bekeplar**
This a preliminary PR
This does the following 
1 - Restructure the project folders
2- Separate users and incidents
3 - Removing Some validation from views.
4- Reducing cognition complexity
Stories attached to this 
[#163286622, #163222381]
screenshots
yoyo
@nearjay06, @James Mudidi, @silver, @masete,@llwasampijja, @sanya-kenneth

### CODE REVIEW

**Comment by wasswa-derick** [comment]
@bekeplar Kindly consult with James to guide on how set up the appropriate PR description or follow this template guide [Pull Request Naming Guide](https://github.com/andela/anbu-rc/wiki/Pull-Request-Naming-Convention)

**Comment by wasswa-derick** [comment]
@bekeplar I notice that you've named your branch as Feedback-two.
Kindly consider renaming this branch name to something descriptive about the task at hand.
For example "ch-application-structure-and-cognitive-complexity-PTBOARDSTORYNUMBER"

**Comment by nearjay06** [comment]
Your repo looks ok, the tests are fine
Just before merging ensure that all the builds pass

**Comment by bekeplar** [comment]
Gonna implement the noted...Thanks

**Pull request merged**
