### PR TITLE
Challenge one feedback

### PR DESCRIPTION
**Pull request by bekeplar**
What this PR does:
- Making all forms centralised
- Removing redundant space on the profile page
- Adding description to records
- Adding more incidents on the list
Stories related to this PR
[#163282748, #163282766, #163282757]
 kindly review to encourage improvements
@nearjay06, @James Mudidi, @llwasampijja, @kalsmic, @nadralia, @mwinel, @masete

### CODE REVIEW

**Comment by wasswa-derick** [comment]
@bekeplar Kindly add screenshots of the changes you've made.

**Comment by wasswa-derick** [comment]
@bekeplar Kindly consider refactoring your PR name and descriptions tailored to this template https://github.com/andela/anbu-rc/wiki/Pull-Request-Naming-Convention

**Comment by mwinel** [comment]
alternatively you could add a link to your github pages in the description.

**Comment by bekeplar** [comment]
Thanks for that clarification

**Pull request merged**
